### ISSUE TITLE
npm run extract-api fail

### ISSUE THREAD

**Issue by yuzhidi** [collibra/api-extractor-example#1]
~/study/api-extractor-example
$ npm run extract-api

> api-extractor-example@1.0.0 extract-api D:\study\api-extractor-example
> npm run compile && npx api-extractor run

> api-extractor-example@1.0.0 compile D:\study\api-extractor-example
> tsc -p .

api-extractor 7.0.17  - https://api-extractor.com/

Using configuration from D:\study\api-extractor-example\api-extractor.json

Missing release tag for ButtonWithDefault in D:/study/api-extractor-example/src/components/ButtonWithDefault.tsx
Missing release tag for ButtonWithStar in D:/study/api-extractor-example/src/components/ButtonWithStar.tsx
(Verbose) Writing: D:\study\api-extractor-example\dist\api-extractor-example.api.json
The API review file has not been set up. Do this by copying temp/api-extractor-example.api.ts to etc/api-extractor-example.api.ts and c
ommitting it.
(Verbose) The "mainDtsRollupPath" is: typings/typings.d.ts
(Verbose) Writing package typings: D:\study\api-extractor-example\dist\typings\typings.d.ts

**Comment by npirotte** [comment]
Hello @yuzhidi 

This repository purpose was to be a hands on example of the setup process af api extractor.

To make it run you have to fix all warnings printed to the console.
* Add release tag (@public) to the two exported components
* Create a `etc` directory and copy the example.api.ts in it.

After these two operations it should run smoothly.

Sory for the confusion, I'll update the readme to explain all these things!
